"""Future-only Shadow positions and executable outcomes."""

from shadow_engine.contracts import (
    ExitReason,
    MaturedOutcome,
    OutcomePath,
    OutcomePoint,
    OutcomeStatus,
    ShadowPolicy,
    ShadowPosition,
)
from shadow_engine.engine import build_outcome_path, mature_outcome, open_position
from shadow_engine.truth import (
    EXECUTION_EVIDENCE_CLASS,
    OUTCOME_CONTRACT_DIGEST,
    OUTCOME_CONTRACT_ID,
    OUTCOME_FACT_SEAL_TYPE,
    OUTCOME_RECEIPT_TYPE,
    POST_EXIT_COUNTERFACTUAL,
    SHADOW_ENTRY_RECEIPT_TYPE,
    CloseObservationStatus,
    ObservedOutcome,
    OutcomeClosePoint,
    OutcomeObservation,
    OutcomePathRole,
    OutcomeReceipt,
    OutcomeTruthPath,
    ShadowAdmission,
    ShadowAdmissionResult,
    ShadowEntryReceipt,
    admit_shadow,
    entry_receipt_payload,
    evaluate_outcome,
    outcome_receipt_payload,
)
from shadow_engine.truth import (
    OutcomeStatus as TruthOutcomeStatus,
)

__all__ = [
    "EXECUTION_EVIDENCE_CLASS",
    "OUTCOME_CONTRACT_DIGEST",
    "OUTCOME_CONTRACT_ID",
    "OUTCOME_FACT_SEAL_TYPE",
    "OUTCOME_RECEIPT_TYPE",
    "POST_EXIT_COUNTERFACTUAL",
    "SHADOW_ENTRY_RECEIPT_TYPE",
    "CloseObservationStatus",
    "ExitReason",
    "MaturedOutcome",
    "ObservedOutcome",
    "OutcomeClosePoint",
    "OutcomeObservation",
    "OutcomePath",
    "OutcomePathRole",
    "OutcomePoint",
    "OutcomeReceipt",
    "OutcomeStatus",
    "OutcomeTruthPath",
    "ShadowAdmission",
    "ShadowAdmissionResult",
    "ShadowEntryReceipt",
    "ShadowPolicy",
    "ShadowPosition",
    "TruthOutcomeStatus",
    "admit_shadow",
    "build_outcome_path",
    "entry_receipt_payload",
    "evaluate_outcome",
    "mature_outcome",
    "open_position",
    "outcome_receipt_payload",
]
