from __future__ import annotations

INVERSE_BTC_RADAR_POLICY_IDENTITY = (
    "sha256:fd604c22b6f4a111955f432fe09647e93c38e914e81c4045905ca79b935bdc9d"
)
INVERSE_BTC_UNDERWRITING_POLICY_IDENTITY = (
    "sha256:933dce3e4d9736b465aaca95a352ef8c3196592bfef04cf1f958442afe0f5e7d"
)
INVERSE_BTC_POSITION_POLICY_IDENTITY = (
    "sha256:8a00bacc13f5f3f2407ea3ff5060464e12d93c3f336f9d1f9d750a0621fa0ffe"
)
ADMISSION_CUTOFF_LEAD_MS = 1_800_000

UNDERWRITING_OBJECT_KINDS = (
    "UNDERWRITING_AVAILABILITY_EVALUATION",
    "UNDERWRITING_ACTION",
    "CANDIDATE_ACTIVATION",
    "CANDIDATE_INVALIDATION",
    "ADMISSION_ATTEMPT_SCHEDULED",
    "ADMISSION_ATTEMPT_TERMINAL",
    "SHADOW_ENTRY",
    "POSITION_EVALUATION",
    "POSITION_ACTION",
    "CLOSE_QUOTE_EVALUATION",
    "POST_CLOSE_ATTEMPT_SCHEDULED",
    "POST_CLOSE_ATTEMPT_TERMINAL",
    "CLOSE_OPPORTUNITY_EVALUATION",
    "SHADOW_CLOSE_OPPORTUNITY",
)

DECISION_CONTROL_OBJECT_KINDS = (
    "UNDERWRITING_DECISION_BATCH_DESIGNATION",
    "SELECTED_UNDERWRITING_DECISION",
    "UNDERWRITING_DECISION_CONTROL_ATTEMPT_SCHEDULED",
    "UNDERWRITING_DECISION_CONTROL_ATTEMPT_TERMINAL",
    "SELECTED_UNDERWRITING_DECISION_CONTROL_OPEN",
    "SELECTED_UNDERWRITING_DECISION_CONTROL_OUTCOME",
    "RADAR_SCORE_BAND_NO_TRADE_CONTROL_OPEN",
    "RADAR_SCORE_BAND_NO_TRADE_CONTROL_OUTCOME",
)

OUTCOME_OBJECT_KINDS = (
    "SHADOW_OUTCOME_OBSERVATION",
    "SHADOW_COUNTERFACTUAL_EXIT",
    "SHADOW_OUTCOME",
)

ALL_DOWNSTREAM_OBJECT_KINDS = (
    UNDERWRITING_OBJECT_KINDS + DECISION_CONTROL_OBJECT_KINDS + OUTCOME_OBJECT_KINDS
)

CANDIDATE_INVALIDATION_REASONS = (
    "RUNTIME_OR_CODE_IDENTITY_CHANGED",
    "RADAR_POLICY_OR_EPISODE_PAUSED_ENDED_OR_CHANGED",
    "UNDERWRITING_OR_POSITION_POLICY_IDENTITY_CHANGED",
    "POSITION_SLOT_CONSUMED_BY_SHADOW_ENTRY",
    "STRUCTURE_LEG_LIFECYCLE_OR_TARGET_QUANTITY_CHANGED",
    "SOURCE_GAP_PLATFORM_DEGRADATION_OR_REQUIRED_FACT_UNKNOWN",
    "LATEST_ADMISSION_BOUNDARY_REACHED",
    "CONSUMED_NON_ADMISSION_BUSINESS_FINGERPRINT_CHANGED",
    "REUNDERWRITING_NO_LONGER_CANDIDATE",
    "FAILED_ADMISSION_EVALUATION_CONSUMED",
)

POSITION_CLOSE_REASONS = (
    "SETTLEMENT_OR_EXPIRY_BOUNDARY_REACHED",
    "LATEST_EXIT_BOUNDARY_REACHED",
    "PLATFORM_OR_SOURCE_DISCONTINUITY",
    "MAXIMUM_NET_LOSS_BOUNDARY_REACHED",
    "SHORT_LEG_RISK_BOUNDARY_REACHED",
    "PATH_OR_JUMP_RISK_BOUNDARY_REACHED",
    "VOLATILITY_STATE_BOUNDARY_REACHED",
    "LIQUIDITY_EXIT_BOUNDARY_REACHED",
    "ECONOMIC_EXIT_BOUNDARY_REACHED",
)
