from __future__ import annotations

RADAR_POLICY_IDENTITY = "sha256:74f286e07f8013e6178b44421db1d4d04808e5e0b0c604a80a0fdbc50f276c21"
UNDERWRITING_POLICY_IDENTITY = (
    "sha256:5cbff45fc342489a0c34b476d1947a54e490e04610dadd7f54a1e18f4681d79a"
)
POSITION_POLICY_IDENTITY = "sha256:e7c38b12cb8c8d79c0f6409ee31289386f7f313a60ef593771648c0504016ef3"

INVERSE_BTC_RADAR_POLICY_IDENTITY = (
    "sha256:283c2a8cc5e14cbed94b0f2a41ddd18ff2410772ae45d07abfea80d04446b1af"
)
INVERSE_BTC_UNDERWRITING_POLICY_IDENTITY = (
    "sha256:76a93725bb4923a70a2865b1e06add3b5a23ae80a831029c558ce188be6e7834"
)
INVERSE_BTC_POSITION_POLICY_IDENTITY = (
    "sha256:cb3866b8efd45d5c05ed23ab56658c2cdbf0359132e39f52ce329761ad933b8e"
)
ADMISSION_CUTOFF_LEAD_MS = 1_800_000

UNDERWRITING_OBJECT_KINDS = (
    "UNDERWRITING_AVAILABILITY_EVALUATION",
    "UNDERWRITING_ACTION",
    "CANDIDATE_ACTIVATION",
    "CANDIDATE_INVALIDATION",
    "ADMISSION_ATTEMPT_SCHEDULED",
    "ADMISSION_ATTEMPT_TERMINAL",
    "SHADOW_ENTRY",
    "POSITION_EVALUATION",
    "POSITION_ACTION",
    "CLOSE_QUOTE_EVALUATION",
    "POST_CLOSE_ATTEMPT_SCHEDULED",
    "POST_CLOSE_ATTEMPT_TERMINAL",
    "CLOSE_OPPORTUNITY_EVALUATION",
    "SHADOW_CLOSE_OPPORTUNITY",
)

DECISION_CONTROL_OBJECT_KINDS = (
    "UNDERWRITING_DECISION_BATCH_DESIGNATION",
    "SELECTED_UNDERWRITING_DECISION",
    "UNDERWRITING_DECISION_CONTROL_ATTEMPT_SCHEDULED",
    "UNDERWRITING_DECISION_CONTROL_ATTEMPT_TERMINAL",
    "SELECTED_UNDERWRITING_DECISION_CONTROL_OPEN",
    "SELECTED_UNDERWRITING_DECISION_CONTROL_OUTCOME",
)

OUTCOME_OBJECT_KINDS = (
    "SHADOW_OUTCOME_OBSERVATION",
    "SHADOW_COUNTERFACTUAL_EXIT",
    "SHADOW_OUTCOME",
)

ALL_DOWNSTREAM_OBJECT_KINDS = (
    UNDERWRITING_OBJECT_KINDS + DECISION_CONTROL_OBJECT_KINDS + OUTCOME_OBJECT_KINDS
)

CANDIDATE_INVALIDATION_REASONS = (
    "RUNTIME_OR_CODE_IDENTITY_CHANGED",
    "RADAR_POLICY_OR_EPISODE_PAUSED_ENDED_OR_CHANGED",
    "UNDERWRITING_OR_POSITION_POLICY_IDENTITY_CHANGED",
    "POSITION_SLOT_CONSUMED_BY_SHADOW_ENTRY",
    "STRUCTURE_LEG_LIFECYCLE_OR_TARGET_QUANTITY_CHANGED",
    "SOURCE_GAP_PLATFORM_DEGRADATION_OR_REQUIRED_FACT_UNKNOWN",
    "LATEST_ADMISSION_BOUNDARY_REACHED",
    "CONSUMED_NON_ADMISSION_BUSINESS_FINGERPRINT_CHANGED",
    "REUNDERWRITING_NO_LONGER_CANDIDATE",
    "FAILED_ADMISSION_EVALUATION_CONSUMED",
)

POSITION_CLOSE_REASONS = (
    "SETTLEMENT_OR_EXPIRY_BOUNDARY_REACHED",
    "LATEST_EXIT_BOUNDARY_REACHED",
    "PLATFORM_OR_SOURCE_DISCONTINUITY",
    "MAXIMUM_NET_LOSS_BOUNDARY_REACHED",
    "SHORT_LEG_RISK_BOUNDARY_REACHED",
    "PATH_OR_JUMP_RISK_BOUNDARY_REACHED",
    "VOLATILITY_STATE_BOUNDARY_REACHED",
    "LIQUIDITY_EXIT_BOUNDARY_REACHED",
    "ECONOMIC_EXIT_BOUNDARY_REACHED",
)

ACTUAL_AVAILABILITY_UNKNOWN = {
    "actual_entry_fee_usdc": "UNKNOWN",
    "actual_close_fee_usdc": "UNKNOWN",
    "actual_total_fee_usdc": "UNKNOWN",
    "actual_pnl_usdc": "UNKNOWN",
    "actual_exposure_quantity_btc": "UNKNOWN",
    "actual_exposure_duration_ms": "UNKNOWN",
    "actual_all_in_loss_usdc": "UNKNOWN",
    "actual_all_in_max_loss_usdc": "UNKNOWN",
    "actual_fill_identity": "UNKNOWN",
    "actual_settlement_cashflow_usdc": "UNKNOWN",
}
