from __future__ import annotations

RADAR_POLICY_IDENTITY = "sha256:8076402f51529fe9d26f4c9f7a76872b5f9490581361c9068370d045511bba0c"
UNDERWRITING_POLICY_IDENTITY = (
    "sha256:29a295b1579e917229e73f8cb85ef57116032ca7e9a5106404d3144dd5f48989"
)
POSITION_POLICY_IDENTITY = "sha256:b99be4299d24db68d9f4734dd755e528a67d7c6f95f38d3db8b47961fe9858af"
ADMISSION_CUTOFF_LEAD_MS = 1_800_000

UNDERWRITING_OBJECT_KINDS = (
    "UNDERWRITING_AVAILABILITY_EVALUATION",
    "UNDERWRITING_ACTION",
    "CANDIDATE_ACTIVATION",
    "CANDIDATE_INVALIDATION",
    "ADMISSION_ATTEMPT_SCHEDULED",
    "ADMISSION_ATTEMPT_TERMINAL",
    "SHADOW_ENTRY",
    "POSITION_EVALUATION",
    "POSITION_ACTION",
    "CLOSE_QUOTE_EVALUATION",
    "POST_CLOSE_ATTEMPT_SCHEDULED",
    "POST_CLOSE_ATTEMPT_TERMINAL",
    "CLOSE_OPPORTUNITY_EVALUATION",
    "SHADOW_CLOSE_OPPORTUNITY",
)

OUTCOME_OBJECT_KINDS = (
    "SHADOW_OUTCOME_OBSERVATION",
    "SHADOW_COUNTERFACTUAL_EXIT",
    "SHADOW_OUTCOME",
)

ALL_DOWNSTREAM_OBJECT_KINDS = UNDERWRITING_OBJECT_KINDS + OUTCOME_OBJECT_KINDS

CANDIDATE_INVALIDATION_REASONS = (
    "RUNTIME_OR_CODE_IDENTITY_CHANGED",
    "RADAR_POLICY_OR_EPISODE_PAUSED_ENDED_OR_CHANGED",
    "UNDERWRITING_OR_POSITION_POLICY_IDENTITY_CHANGED",
    "POSITION_SLOT_CONSUMED_BY_SHADOW_ENTRY",
    "STRUCTURE_LEG_LIFECYCLE_OR_TARGET_QUANTITY_CHANGED",
    "SOURCE_GAP_PLATFORM_DEGRADATION_OR_REQUIRED_FACT_UNKNOWN",
    "LATEST_ADMISSION_BOUNDARY_REACHED",
    "CONSUMED_NON_ADMISSION_BUSINESS_FINGERPRINT_CHANGED",
    "REUNDERWRITING_NO_LONGER_CANDIDATE",
    "FAILED_ADMISSION_EVALUATION_CONSUMED",
)

POSITION_CLOSE_REASONS = (
    "SETTLEMENT_OR_EXPIRY_BOUNDARY_REACHED",
    "LATEST_EXIT_BOUNDARY_REACHED",
    "PLATFORM_OR_SOURCE_DISCONTINUITY",
    "MAXIMUM_NET_LOSS_BOUNDARY_REACHED",
    "SHORT_LEG_RISK_BOUNDARY_REACHED",
    "PATH_OR_JUMP_RISK_BOUNDARY_REACHED",
    "VOLATILITY_STATE_BOUNDARY_REACHED",
    "LIQUIDITY_EXIT_BOUNDARY_REACHED",
    "ECONOMIC_EXIT_BOUNDARY_REACHED",
)

ACTUAL_AVAILABILITY_UNKNOWN = {
    "actual_entry_fee_usdc": "UNKNOWN",
    "actual_close_fee_usdc": "UNKNOWN",
    "actual_total_fee_usdc": "UNKNOWN",
    "actual_pnl_usdc": "UNKNOWN",
    "actual_exposure_quantity_btc": "UNKNOWN",
    "actual_exposure_duration_ms": "UNKNOWN",
    "actual_all_in_loss_usdc": "UNKNOWN",
    "actual_all_in_max_loss_usdc": "UNKNOWN",
    "actual_fill_identity": "UNKNOWN",
    "actual_settlement_cashflow_usdc": "UNKNOWN",
}
