from __future__ import annotations

from short_vol_underwriting.constants import ALL_DOWNSTREAM_OBJECT_KINDS

# The tuples are executable closed schemas. They intentionally preserve contract declaration order
# for golden tests even though durable object files use bytewise key sorting.
PAYLOAD_KEYS: dict[str, tuple[str, ...]] = {
    "UNDERWRITING_AVAILABILITY_EVALUATION": (
        "underwriting_availability_evaluation_identity",
        "radar_scope_or_short_leg_identity",
        "consumed_availability_fact_fingerprint",
        "availability",
        "availability_evaluation_fact_boundary",
        "unknown_reasons",
    ),
    "UNDERWRITING_ACTION": (
        "underwriting_action_identity",
        "underwriting_availability_evaluation_identity",
        "underwriting_opportunity_key_identity",
        "consumed_economic_fact_fingerprint",
        "economic_action",
        "evaluation_fact_boundary",
        "gross_entry_credit_usdc",
        "entry_fee_reserve_usdc",
        "net_entry_credit_usdc",
        "payoff_cap_usdc",
        "contractual_payoff_max_loss_ex_fees_usdc",
        "entry_fee_reserved_payoff_loss_usdc",
        "future_cost_reserve_usdc",
        "underwriting_reserved_loss_usdc",
        "actual_all_in_max_loss_usdc",
        "actual_all_in_max_loss_availability",
    ),
    "CANDIDATE_ACTIVATION": (
        "candidate_identity",
        "underwriting_action_identity",
        "underwriting_position_slot_key_identity",
        "candidate_activation_fact_boundary",
    ),
    "CANDIDATE_INVALIDATION": (
        "candidate_invalidation_identity",
        "candidate_identity",
        "primary_reason",
        "ordered_applicable_reason_vector",
        "terminal_fact_boundary",
    ),
    "ADMISSION_ATTEMPT_SCHEDULED": (
        "scheduled_admission_attempt_identity",
        "candidate_identity",
        "request_id",
        "request_method",
        "request_params",
        "schedule_fact_boundary",
    ),
    "ADMISSION_ATTEMPT_TERMINAL": (
        "admission_attempt_terminal_identity",
        "scheduled_admission_attempt_identity",
        "candidate_identity",
        "terminal_outcome",
        "terminal_fact_boundary",
        "terminal_source_identity",
        "matched_response_identity",
    ),
    "SHADOW_ENTRY": (
        "shadow_entry_identity",
        "candidate_identity",
        "admission_attempt_terminal_identity",
        "underwriting_position_slot_key_identity",
        "entry_fact_boundary",
        "canonical_combo_identity",
        "canonical_leg_identities",
        "entry_direction",
        "full_quantity_btc",
        "entry_consumed_levels",
        "entry_combo_quote_source_ref",
        "entry_commission_source_refs",
        "entry_index_usdc_per_btc",
        "entry_index_source_ref",
        "entry_short_leg_mark_iv_fraction",
        "entry_short_leg_mark_iv_source_ref",
        "gross_entry_credit_usdc",
        "entry_fee_reserve_usdc",
        "net_entry_credit_usdc",
        "contractual_payoff_max_loss_ex_fees_usdc",
        "entry_fee_reserved_payoff_loss_usdc",
        "future_cost_reserve_usdc",
        "underwriting_reserved_loss_usdc",
        "actual_all_in_max_loss_usdc",
        "actual_all_in_max_loss_availability",
    ),
    "POSITION_EVALUATION": (
        "position_evaluation_identity",
        "shadow_entry_identity",
        "consumed_position_fact_fingerprint",
        "evaluation_fact_boundary",
        "ordered_predicate_truth_vector",
        "entry_index_usdc_per_btc",
        "entry_index_source_identity",
        "entry_index_fact_boundary",
        "entry_short_leg_mark_iv_fraction",
        "entry_short_leg_mark_iv_source_identity",
        "entry_short_leg_mark_iv_fact_boundary",
        "prior_evaluation_index_usdc_per_btc",
        "prior_evaluation_index_source_identity",
        "prior_evaluation_index_fact_boundary",
        "current_index_usdc_per_btc",
        "current_index_source_identity",
        "current_index_fact_boundary",
        "current_index_availability",
        "next_evaluation_index_usdc_per_btc",
    ),
    "POSITION_ACTION": (
        "position_action_identity",
        "position_evaluation_identity",
        "serialized_action",
        "ordered_predicate_truth_vector",
        "ordered_latched_close_reason_vector",
        "primary_close_reason",
        "secondary_close_reasons",
        "first_latched_close_action_identity",
        "scheduled_post_close_attempt_identity",
        "action_fact_boundary",
    ),
    "CLOSE_QUOTE_EVALUATION": (
        "close_quote_evaluation_identity",
        "shadow_entry_identity",
        "first_latched_close_action_identity",
        "canonical_combo_identity",
        "canonical_leg_identities",
        "close_direction",
        "full_quantity_btc",
        "consumed_rule_scoped_quote_fingerprint",
        "close_quote_state",
        "close_conditioning",
        "consumed_levels",
        "gross_close_cashflow_usdc",
        "evaluation_fact_boundary",
    ),
    "POST_CLOSE_ATTEMPT_SCHEDULED": (
        "scheduled_post_close_attempt_identity",
        "shadow_entry_identity",
        "first_latched_close_action_identity",
        "request_id_or_marker",
        "request_method",
        "request_params",
        "schedule_fact_boundary",
    ),
    "POST_CLOSE_ATTEMPT_TERMINAL": (
        "post_close_attempt_terminal_identity",
        "scheduled_post_close_attempt_identity",
        "terminal_status",
        "terminal_owner",
        "terminal_fact_boundary",
        "matched_response_identity",
    ),
    "CLOSE_OPPORTUNITY_EVALUATION": (
        "close_opportunity_evaluation_identity",
        "shadow_entry_identity",
        "first_latched_close_action_identity",
        "close_quote_evaluation_identity",
        "attempt_terminal_identity",
        "attempt_terminal_fact_boundary",
        "opportunity_economics_business_fingerprint",
        "eligibility",
        "eligibility_reason",
        "evaluation_fact_boundary",
        "gross_close_cashflow_usdc",
        "gross_cashflow_availability",
        "short_leg_taker_commission_fraction",
        "long_leg_taker_commission_fraction",
        "commission_source_refs",
        "close_index_usdc_per_btc",
        "index_source_ref",
        "close_fee_reserve_usdc",
        "net_close_cashflow_usdc",
        "net_close_debit_usdc",
        "projected_shadow_net_pnl_usdc",
        "projected_net_loss_usdc",
        "derived_economics_availability",
    ),
    "SHADOW_CLOSE_OPPORTUNITY": (
        "shadow_close_opportunity_identity",
        "close_opportunity_evaluation_identity",
        "shadow_entry_identity",
        "first_latched_close_action_identity",
        "opportunity_fact_boundary",
        "canonical_combo_identity",
        "canonical_leg_identities",
        "close_direction",
        "full_quantity_btc",
        "consumed_levels",
        "commission_source_refs",
        "index_source_ref",
        "gross_close_cashflow_usdc",
        "close_fee_reserve_usdc",
        "net_close_cashflow_usdc",
        "net_close_debit_usdc",
        "projected_shadow_net_pnl_usdc",
        "projected_net_loss_usdc",
    ),
    "SHADOW_OUTCOME_OBSERVATION": (
        "shadow_observation_identity",
        "shadow_entry_identity",
        "start_fact_boundary",
        "aligned_pair_identity",
        "cohort_enrolled",
        "lifecycle_state",
    ),
    "SHADOW_COUNTERFACTUAL_EXIT": (
        "shadow_counterfactual_exit_identity",
        "shadow_observation_identity",
        "first_latched_close_action_identity",
        "close_opportunity_evaluation_identity",
        "shadow_close_opportunity_identity",
        "selection_fact_boundary",
        "first_latched_close_action_fact_boundary",
        "close_opportunity_evaluation_fact_boundary",
        "combo_quote_source_ref",
        "commission_source_refs",
        "index_source_ref",
        "canonical_combo_identity",
        "canonical_leg_identities",
        "close_direction",
        "full_quantity_btc",
        "consumed_levels",
        "short_leg_taker_commission_fraction",
        "long_leg_taker_commission_fraction",
        "close_index_usdc_per_btc",
        "gross_close_cashflow_usdc",
        "close_fee_reserve_usdc",
        "net_close_cashflow_usdc",
        "net_close_debit_usdc",
        "projected_shadow_net_pnl_usdc",
        "projected_net_loss_usdc",
    ),
    "SHADOW_OUTCOME": (
        "shadow_outcome_identity",
        "shadow_observation_identity",
        "shadow_entry_identity",
        "terminal_state",
        "terminal_fact_boundary",
        "selected_exit_identity",
        "first_latched_close_action_identity",
        "first_latched_close_action_fact_boundary",
        "scheduled_post_close_attempt_identity",
        "scheduled_post_close_attempt_fact_boundary",
        "post_close_attempt_terminal_identity",
        "post_close_attempt_terminal_status",
        "post_close_attempt_terminal_owner",
        "post_close_attempt_terminal_fact_boundary",
        "natural_terminal_lifecycle_witnesses",
        "censor_mask",
        "terminal_supervisor_source_identity",
        "gross_entry_credit_usdc",
        "entry_fee_reserve_usdc",
        "net_entry_credit_usdc",
        "contractual_payoff_max_loss_ex_fees_usdc",
        "entry_fee_reserved_payoff_loss_usdc",
        "underwriting_reserved_loss_usdc",
        "gross_close_cashflow_usdc",
        "close_fee_reserve_usdc",
        "net_close_cashflow_usdc",
        "gross_pnl_usdc",
        "total_public_fee_reserve_usdc",
        "net_pnl_after_public_standard_fee_reserve_usdc",
        "net_loss_usdc",
        "economic_availability",
        "actual_entry_fee_usdc",
        "actual_close_fee_usdc",
        "actual_total_fee_usdc",
        "actual_pnl_usdc",
        "actual_exposure_quantity_btc",
        "actual_exposure_duration_ms",
        "actual_all_in_loss_usdc",
        "actual_all_in_max_loss_usdc",
        "actual_fill_identity",
        "actual_settlement_cashflow_usdc",
        "actual_availability",
    ),
    "REJECTED_COUNTERFACTUAL_ANCHOR": (
        "rejected_anchor_identity",
        "underwriting_position_slot_key",
        "underwriting_action_identity",
        "underwriting_action",
        "anchor_fact_boundary",
        "canonical_combo_identity",
        "canonical_leg_identities",
        "entry_direction",
        "full_quantity_btc",
        "entry_consumed_levels",
        "entry_combo_quote_source_ref",
        "entry_commission_source_refs",
        "entry_index_usdc_per_btc",
        "entry_index_source_identity",
        "entry_index_fact_boundary",
        "entry_short_leg_mark_iv_fraction",
        "entry_short_leg_mark_iv_source_identity",
        "entry_short_leg_mark_iv_fact_boundary",
        "gross_entry_credit_usdc",
        "entry_fee_reserve_usdc",
        "net_entry_credit_usdc",
        "contractual_payoff_max_loss_ex_fees_usdc",
        "entry_fee_reserved_payoff_loss_usdc",
        "underwriting_reserved_loss_usdc",
    ),
    "REJECTED_COUNTERFACTUAL_OBSERVATION": (
        "rejected_observation_identity",
        "rejected_anchor_identity",
        "start_fact_boundary",
        "aligned_pair_identity",
        "cohort_enrolled",
        "lifecycle_state",
    ),
    "REJECTED_COUNTERFACTUAL_POSITION_EVALUATION": (
        "rejected_position_evaluation_identity",
        "rejected_observation_identity",
        "consumed_position_fact_fingerprint",
        "evaluation_fact_boundary",
        "ordered_predicate_truth_vector",
        "entry_index_usdc_per_btc",
        "entry_index_source_identity",
        "entry_index_fact_boundary",
        "entry_short_leg_mark_iv_fraction",
        "entry_short_leg_mark_iv_source_identity",
        "entry_short_leg_mark_iv_fact_boundary",
        "prior_evaluation_index_usdc_per_btc",
        "prior_evaluation_index_source_identity",
        "prior_evaluation_index_fact_boundary",
        "current_index_usdc_per_btc",
        "current_index_source_identity",
        "current_index_fact_boundary",
        "current_index_availability",
        "next_evaluation_index_usdc_per_btc",
    ),
    "REJECTED_COUNTERFACTUAL_POSITION_ACTION": (
        "rejected_position_action_identity",
        "rejected_position_evaluation_identity",
        "serialized_action",
        "ordered_predicate_truth_vector",
        "ordered_latched_close_reason_vector",
        "first_latched_close_action_identity",
        "scheduled_post_close_attempt_identity",
        "action_fact_boundary",
    ),
    "REJECTED_COUNTERFACTUAL_CLOSE_QUOTE_EVALUATION": (
        "rejected_close_quote_evaluation_identity",
        "rejected_observation_identity",
        "first_latched_close_action_identity",
        "canonical_combo_identity",
        "canonical_leg_identities",
        "close_direction",
        "full_quantity_btc",
        "consumed_rule_scoped_quote_fingerprint",
        "close_quote_state",
        "close_conditioning",
        "consumed_levels",
        "gross_close_cashflow_usdc",
        "evaluation_fact_boundary",
    ),
    "REJECTED_COUNTERFACTUAL_CLOSE_OPPORTUNITY_EVALUATION": (
        "rejected_close_opportunity_evaluation_identity",
        "rejected_observation_identity",
        "first_latched_close_action_identity",
        "close_quote_evaluation_identity",
        "attempt_terminal_identity",
        "attempt_terminal_fact_boundary",
        "opportunity_economics_business_fingerprint",
        "eligibility",
        "eligibility_reason",
        "evaluation_fact_boundary",
        "gross_close_cashflow_usdc",
        "gross_cashflow_availability",
        "short_leg_taker_commission_fraction",
        "long_leg_taker_commission_fraction",
        "commission_source_refs",
        "close_index_usdc_per_btc",
        "index_source_ref",
        "close_fee_reserve_usdc",
        "net_close_cashflow_usdc",
        "net_close_debit_usdc",
        "projected_shadow_net_pnl_usdc",
        "projected_net_loss_usdc",
        "derived_economics_availability",
    ),
    "REJECTED_COUNTERFACTUAL_EXIT": (
        "rejected_exit_identity",
        "rejected_observation_identity",
        "first_latched_close_action_identity",
        "close_quote_evaluation_identity",
        "close_opportunity_evaluation_identity",
        "selection_fact_boundary",
        "first_latched_close_action_fact_boundary",
        "close_quote_evaluation_fact_boundary",
        "close_opportunity_evaluation_fact_boundary",
        "consumed_rule_scoped_quote_fingerprint",
        "commission_source_refs",
        "index_source_ref",
        "canonical_combo_identity",
        "canonical_leg_identities",
        "close_direction",
        "full_quantity_btc",
        "consumed_levels",
        "short_leg_taker_commission_fraction",
        "long_leg_taker_commission_fraction",
        "close_index_usdc_per_btc",
        "gross_close_cashflow_usdc",
        "close_fee_reserve_usdc",
        "net_close_cashflow_usdc",
        "net_close_debit_usdc",
        "projected_shadow_net_pnl_usdc",
        "projected_net_loss_usdc",
    ),
    "REJECTED_COUNTERFACTUAL_OUTCOME": (
        "rejected_outcome_identity",
        "rejected_observation_identity",
        "rejected_anchor_identity",
        "terminal_state",
        "terminal_fact_boundary",
        "selected_exit_identity",
        "first_latched_close_action_identity",
        "first_latched_close_action_fact_boundary",
        "scheduled_post_close_attempt_identity",
        "scheduled_post_close_attempt_fact_boundary",
        "post_close_attempt_terminal_identity",
        "post_close_attempt_terminal_status",
        "post_close_attempt_terminal_owner",
        "post_close_attempt_terminal_fact_boundary",
        "natural_terminal_lifecycle_witnesses",
        "censor_mask",
        "terminal_supervisor_source_identity",
        "gross_entry_credit_usdc",
        "entry_fee_reserve_usdc",
        "net_entry_credit_usdc",
        "contractual_payoff_max_loss_ex_fees_usdc",
        "entry_fee_reserved_payoff_loss_usdc",
        "underwriting_reserved_loss_usdc",
        "gross_close_cashflow_usdc",
        "close_fee_reserve_usdc",
        "net_close_cashflow_usdc",
        "gross_pnl_usdc",
        "total_public_fee_reserve_usdc",
        "net_pnl_after_public_standard_fee_reserve_usdc",
        "net_loss_usdc",
        "economic_availability",
        "actual_entry_fee_usdc",
        "actual_close_fee_usdc",
        "actual_total_fee_usdc",
        "actual_pnl_usdc",
        "actual_exposure_quantity_btc",
        "actual_exposure_duration_ms",
        "actual_all_in_loss_usdc",
        "actual_all_in_max_loss_usdc",
        "actual_fill_identity",
        "actual_settlement_cashflow_usdc",
        "actual_availability",
    ),
    "ALIGNED_POLICY_NO_TRADE_PAIR": (
        "aligned_pair_identity",
        "pair_family",
        "cohort_enrolled",
        "pair_anchor_identity",
        "policy_arm",
        "alternative_arm",
        "trade_observation_identity",
        "trade_outcome_identity",
        "terminal_state",
        "terminal_fact_boundary",
        "censor_mask",
        "no_trade_cashflow_usdc",
        "trade_net_pnl_after_public_standard_fee_reserve_usdc",
        "policy_advantage_usdc",
        "comparison_availability",
    ),
}

IDENTITY_PAYLOAD_FIELDS = {kind: keys[0] for kind, keys in PAYLOAD_KEYS.items()}

PRIMARY_BOUNDARY_FIELDS = {
    "UNDERWRITING_AVAILABILITY_EVALUATION": "availability_evaluation_fact_boundary",
    "UNDERWRITING_ACTION": "evaluation_fact_boundary",
    "CANDIDATE_ACTIVATION": "candidate_activation_fact_boundary",
    "CANDIDATE_INVALIDATION": "terminal_fact_boundary",
    "ADMISSION_ATTEMPT_SCHEDULED": "schedule_fact_boundary",
    "ADMISSION_ATTEMPT_TERMINAL": "terminal_fact_boundary",
    "SHADOW_ENTRY": "entry_fact_boundary",
    "POSITION_EVALUATION": "evaluation_fact_boundary",
    "POSITION_ACTION": "action_fact_boundary",
    "CLOSE_QUOTE_EVALUATION": "evaluation_fact_boundary",
    "POST_CLOSE_ATTEMPT_SCHEDULED": "schedule_fact_boundary",
    "POST_CLOSE_ATTEMPT_TERMINAL": "terminal_fact_boundary",
    "CLOSE_OPPORTUNITY_EVALUATION": "evaluation_fact_boundary",
    "SHADOW_CLOSE_OPPORTUNITY": "opportunity_fact_boundary",
    "SHADOW_OUTCOME_OBSERVATION": "start_fact_boundary",
    "SHADOW_COUNTERFACTUAL_EXIT": "selection_fact_boundary",
    "SHADOW_OUTCOME": "terminal_fact_boundary",
    "REJECTED_COUNTERFACTUAL_ANCHOR": "anchor_fact_boundary",
    "REJECTED_COUNTERFACTUAL_OBSERVATION": "start_fact_boundary",
    "REJECTED_COUNTERFACTUAL_POSITION_EVALUATION": "evaluation_fact_boundary",
    "REJECTED_COUNTERFACTUAL_POSITION_ACTION": "action_fact_boundary",
    "REJECTED_COUNTERFACTUAL_CLOSE_QUOTE_EVALUATION": "evaluation_fact_boundary",
    "REJECTED_COUNTERFACTUAL_CLOSE_OPPORTUNITY_EVALUATION": "evaluation_fact_boundary",
    "REJECTED_COUNTERFACTUAL_EXIT": "selection_fact_boundary",
    "REJECTED_COUNTERFACTUAL_OUTCOME": "terminal_fact_boundary",
    "ALIGNED_POLICY_NO_TRADE_PAIR": "terminal_fact_boundary",
}

if set(PAYLOAD_KEYS) != set(ALL_DOWNSTREAM_OBJECT_KINDS):
    raise RuntimeError("downstream payload schema registry is incomplete")
